/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as i0 from '@angular/core';
import * as i1 from './ng2';
import * as i2 from '@angular/common';
import * as i3 from '@angular/platform-browser';
import * as i4 from '@angular/animations/browser';
import * as i5 from '@angular/platform-browser/animations';
import * as i6 from '@angular/animations';
export const AppModuleNgFactory:i0.NgModuleFactory<i1.AppModule> = i0.ɵcmf(i1.AppModule,
    ([] as any[]),(_l:any) => {
      return i0.ɵmod([i0.ɵmpd(512,i0.ComponentFactoryResolver,i0.ɵCodegenComponentFactoryResolver,
          [[8,[Ng2ComponentNgFactory]],[3,i0.ComponentFactoryResolver],i0.NgModuleRef]),
          i0.ɵmpd(5120,i0.LOCALE_ID,i0.ɵo,[[3,i0.LOCALE_ID]]),i0.ɵmpd(4608,i2.NgLocalization,
              i2.NgLocaleLocalization,[i0.LOCALE_ID,[2,i2.ɵa]]),i0.ɵmpd(4608,i0.Compiler,
              i0.Compiler,([] as any[])),i0.ɵmpd(5120,i0.APP_ID,i0.ɵh,([] as any[])),
          i0.ɵmpd(5120,i0.IterableDiffers,i0.ɵm,([] as any[])),i0.ɵmpd(5120,i0.KeyValueDiffers,
              i0.ɵn,([] as any[])),i0.ɵmpd(4608,i3.DomSanitizer,i3.ɵd,[i2.DOCUMENT]),
          i0.ɵmpd(6144,i0.Sanitizer,(null as any),[i3.DomSanitizer]),i0.ɵmpd(4608,
              i3.HAMMER_GESTURE_CONFIG,i3.HammerGestureConfig,([] as any[])),i0.ɵmpd(5120,
              i3.EVENT_MANAGER_PLUGINS,(p0_0:any,p0_1:any,p1_0:any,p2_0:any,p2_1:any) => {
                return [new i3.ɵDomEventsPlugin(p0_0,p0_1),new i3.ɵKeyEventsPlugin(p1_0),
                    new i3.ɵHammerGesturesPlugin(p2_0,p2_1)];
              },[i2.DOCUMENT,i0.NgZone,i2.DOCUMENT,i2.DOCUMENT,i3.HAMMER_GESTURE_CONFIG]),
          i0.ɵmpd(4608,i3.EventManager,i3.EventManager,[i3.EVENT_MANAGER_PLUGINS,i0.NgZone]),
          i0.ɵmpd(135680,i3.ɵDomSharedStylesHost,i3.ɵDomSharedStylesHost,[i2.DOCUMENT]),
          i0.ɵmpd(4608,i3.ɵDomRendererFactory2,i3.ɵDomRendererFactory2,[i3.EventManager,
              i3.ɵDomSharedStylesHost]),i0.ɵmpd(5120,i4.AnimationDriver,i5.ɵc,([] as any[])),
          i0.ɵmpd(5120,i4.ɵAnimationStyleNormalizer,i5.ɵd,([] as any[])),i0.ɵmpd(4608,
              i4.ɵAnimationEngine,i5.ɵb,[i4.AnimationDriver,i4.ɵAnimationStyleNormalizer]),
          i0.ɵmpd(5120,i0.RendererFactory2,i5.ɵe,[i3.ɵDomRendererFactory2,i4.ɵAnimationEngine,
              i0.NgZone]),i0.ɵmpd(6144,i3.ɵSharedStylesHost,(null as any),[i3.ɵDomSharedStylesHost]),
          i0.ɵmpd(4608,i0.Testability,i0.Testability,[i0.NgZone]),i0.ɵmpd(4608,i3.Meta,
              i3.Meta,[i2.DOCUMENT]),i0.ɵmpd(4608,i3.Title,i3.Title,[i2.DOCUMENT]),
          i0.ɵmpd(4608,i6.AnimationBuilder,i5.ɵBrowserAnimationBuilder,[i0.RendererFactory2,
              i3.DOCUMENT]),i0.ɵmpd(512,i2.CommonModule,i2.CommonModule,([] as any[])),
          i0.ɵmpd(1024,i0.ErrorHandler,i3.ɵa,([] as any[])),i0.ɵmpd(1024,i0.APP_INITIALIZER,
              (p0_0:any) => {
                return [i3.ɵg(p0_0)];
              },[[2,i0.NgProbeToken]]),i0.ɵmpd(512,i0.ApplicationInitStatus,i0.ApplicationInitStatus,
              [[2,i0.APP_INITIALIZER]]),i0.ɵmpd(131584,i0.ɵg,i0.ɵg,[i0.NgZone,i0.ɵConsole,
              i0.Injector,i0.ErrorHandler,i0.ComponentFactoryResolver,i0.ApplicationInitStatus]),
          i0.ɵmpd(2048,i0.ApplicationRef,(null as any),[i0.ɵg]),i0.ɵmpd(512,i0.ApplicationModule,
              i0.ApplicationModule,[i0.ApplicationRef]),i0.ɵmpd(512,i3.BrowserModule,
              i3.BrowserModule,[[3,i3.BrowserModule]]),i0.ɵmpd(512,i5.BrowserAnimationsModule,
              i5.BrowserAnimationsModule,([] as any[])),i0.ɵmpd(512,i1.AppModule,i1.AppModule,
              ([] as any[]))]);
    });
const styles_Ng2Component:any[] = ([] as any[]);
export const RenderType_Ng2Component:i0.RendererType2 = i0.ɵcrt({encapsulation:2,styles:styles_Ng2Component,
    data:{}});
export function View_Ng2Component_0(_l:any):i0.ɵViewDefinition {
  return i0.ɵvid(0,[(_l()(),i0.ɵted((null as any),['\n    '])),(_l()(),i0.ɵeld(0,(null as any),
      (null as any),1,'h2',([] as any[]),(null as any),(null as any),(null as any),
      (null as any),(null as any))),(_l()(),i0.ɵted((null as any),['ng2'])),(_l()(),
      i0.ɵted((null as any),['\n    '])),(_l()(),i0.ɵeld(0,(null as any),(null as any),
      1,'button',([] as any[]),(null as any),[[(null as any),'click']],(_v,en,$event) => {
        var ad:boolean = true;
        var _co:i1.Ng2Component = _v.component;
        if (('click' === en)) {
          const pd_0:any = ((<any>_co.clickButton()) !== false);
          ad = (pd_0 && ad);
        }
        return ad;
      },(null as any),(null as any))),(_l()(),i0.ɵted((null as any),['Click Count: ',
      ''])),(_l()(),i0.ɵted((null as any),['\n  ']))],(null as any),(_ck,_v) => {
    var _co:i1.Ng2Component = _v.component;
    const currVal_0:any = _co.callCount;
    _ck(_v,5,0,currVal_0);
  });
}
export function View_Ng2Component_Host_0(_l:any):i0.ɵViewDefinition {
  return i0.ɵvid(0,[(_l()(),i0.ɵeld(0,(null as any),(null as any),1,'ng2',([] as any[]),
      (null as any),(null as any),(null as any),View_Ng2Component_0,RenderType_Ng2Component)),
      i0.ɵdid(49152,(null as any),0,i1.Ng2Component,([] as any[]),(null as any),(null as any))],
      (null as any),(null as any));
}
export const Ng2ComponentNgFactory:i0.ComponentFactory<i1.Ng2Component> = i0.ɵccf('ng2',
    i1.Ng2Component,View_Ng2Component_Host_0,{},{},([] as any[]));
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiL3Vzci9sb2NhbC9nb29nbGUvaG9tZS9xaXlpL3Byb3RyYWN0b3IvdGVzdGFwcC91cGdyYWRlL2FwcC9kb3duZ3JhZGUvbmcyLm5nZmFjdG9yeS50cyIsInZlcnNpb24iOjMsInNvdXJjZVJvb3QiOiIiLCJzb3VyY2VzIjpbIm5nOi8vL3Vzci9sb2NhbC9nb29nbGUvaG9tZS9xaXlpL3Byb3RyYWN0b3IvdGVzdGFwcC91cGdyYWRlL2FwcC9kb3duZ3JhZGUvbmcyLnRzIiwibmc6Ly8vdXNyL2xvY2FsL2dvb2dsZS9ob21lL3FpeWkvcHJvdHJhY3Rvci90ZXN0YXBwL3VwZ3JhZGUvYXBwL2Rvd25ncmFkZS9uZzIudHMuTmcyQ29tcG9uZW50Lmh0bWwiLCJuZzovLy91c3IvbG9jYWwvZ29vZ2xlL2hvbWUvcWl5aS9wcm90cmFjdG9yL3Rlc3RhcHAvdXBncmFkZS9hcHAvZG93bmdyYWRlL25nMi50cy5OZzJDb21wb25lbnRfSG9zdC5odG1sIl0sInNvdXJjZXNDb250ZW50IjpbIiAiLCJcbiAgICA8aDI+bmcyPC9oMj5cbiAgICA8YnV0dG9uIChjbGljayk9J2NsaWNrQnV0dG9uKCknPkNsaWNrIENvdW50OiB7e2NhbGxDb3VudH19PC9idXR0b24+XG4gICIsIjxuZzI+PC9uZzI+Il0sIm1hcHBpbmdzIjoiQUFBQTs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7OztvQkNBQSwyQ0FDSTtNQUFBO01BQUEsOEJBQUksd0NBQVE7YUFBQSw0QkFDWjtNQUFBO1FBQUE7UUFBQTtRQUFRO1VBQUE7VUFBQTtRQUFBO1FBQVI7TUFBQSxnQ0FBZ0M7TUFBQSxNQUFtQzs7SUFBbkM7SUFBQTs7OztvQkNGcEM7TUFBQTthQUFBOzs7OyJ9
