/// <reference path="../../built/ambient.d.ts" />
import {ProtractorBy} from 'protractor';
let by: ProtractorBy;
let By: ProtractorBy;
by.addLocator(0, () => {});
by.addLocator(() => {}, () => {});
by.addLocator('', () => {}, () => {});
by.addLocator('', '', '');
by.binding(0);
by.binding(true);
by.binding(() => {});
by.binding();
by.binding('', '');
by.exactBinding(0);
by.exactBinding(true);
by.exactBinding(() => {});
by.exactBinding();
by.exactBinding('', '');
by.model(0);
by.model(true);
by.model(() => {});
by.model();
by.model('', '');
by.buttonText(0);
by.buttonText(true);
by.buttonText(() => {});
by.buttonText();
by.buttonText('', '');
by.partialButtonText(0);
by.partialButtonText(true);
by.partialButtonText(() => {});
by.partialButtonText();
by.partialButtonText('', '');
by.repeater(0);
by.repeater(true);
by.repeater(() => {});
by.repeater();
by.repeater('', '');
by.exactRepeater(0);
by.exactRepeater(true);
by.exactRepeater(() => {});
by.exactRepeater();
by.exactRepeater('', '');
by.cssContainingText(0);
by.cssContainingText(true);
by.cssContainingText(() => {});
by.cssContainingText();
by.cssContainingText('', 0);
by.cssContainingText(0, 0);
by.cssContainingText(0, '1');
by.cssContainingText('0', '1', '2');
by.options(0);
by.options(true);
by.options(() => {});
by.options();
by.options('', '');
by.deepCss(0);
by.deepCss(true);
by.deepCss(() => {});
by.deepCss();
by.deepCss('', '');
by.className(0);
by.className(true);
by.className(() => {});
by.className();
by.className('', '');
by.css(0);
by.css(true);
by.css(() => {});
by.css();
by.css('', '');
by.id(0);
by.id(true);
by.id(() => {});
by.id();
by.id('', '');
by.linkText(0);
by.linkText(true);
by.linkText(() => {});
by.linkText();
by.linkText('', '');
by.js(0);
by.js(true);
by.js(() => {});
by.js();
by.js('', '');
by.name(0);
by.name(true);
by.name(() => {});
by.name();
by.name('', '');
by.partialLinkText(0);
by.partialLinkText(true);
by.partialLinkText(() => {});
by.partialLinkText();
by.partialLinkText('', '');
by.tagName(0);
by.tagName(true);
by.tagName(() => {});
by.tagName();
by.tagName('', '');
by.xpath(0);
by.xpath(true);
by.xpath(() => {});
by.xpath();
by.xpath('', '');
By.addLocator(0, () => {});
By.addLocator(() => {}, () => {});
By.addLocator(true, () => {});
By.addLocator('', () => {}, () => {});
By.addLocator('', '', '');
By.binding(0);
By.binding(true);
By.binding(() => {});
By.binding();
By.binding('', '');
By.exactBinding(0);
By.exactBinding(true);
By.exactBinding(() => {});
By.exactBinding();
By.exactBinding('', '');
By.model(0);
By.model(true);
By.model(() => {});
By.model();
By.model('', '');
By.buttonText(0);
By.buttonText(true);
By.buttonText(() => {});
By.buttonText();
By.buttonText('', '');
By.partialButtonText(0);
By.partialButtonText(true);
By.partialButtonText(() => {});
By.partialButtonText();
By.partialButtonText('', '');
By.repeater(0);
By.repeater(true);
By.repeater(() => {});
By.repeater();
By.repeater('', '');
By.exactRepeater(0);
By.exactRepeater(true);
By.exactRepeater(() => {});
By.exactRepeater();
By.exactRepeater('', '');
By.cssContainingText(0);
By.cssContainingText(true);
By.cssContainingText(() => {});
By.cssContainingText();
By.cssContainingText('', 0);
By.cssContainingText(0, 0);
By.cssContainingText(0, '1');
By.cssContainingText('0', '1', '2');
By.options(0);
By.options(true);
By.options(() => {});
By.options();
By.options('', '');
By.deepCss(0);
By.deepCss(true);
By.deepCss(() => {});
By.deepCss();
By.deepCss('', '');
By.className(0);
By.className(true);
By.className(() => {});
By.className();
By.className('', '');
By.css(0);
By.css(true);
By.css(() => {});
By.css();
By.css('', '');
By.id(0);
By.id(true);
By.id(() => {});
By.id();
By.id('', '');
By.linkText(0);
By.linkText(true);
By.linkText(() => {});
By.linkText();
By.linkText('', '');
By.js(0);
By.js(true);
By.js(() => {});
By.js();
By.js('', '');
By.name(0);
By.name(true);
By.name(() => {});
By.name();
By.name('', '');
By.partialLinkText(0);
By.partialLinkText(true);
By.partialLinkText(() => {});
By.partialLinkText();
By.partialLinkText('', '');
By.tagName(0);
By.tagName(true);
By.tagName(() => {});
By.tagName();
By.tagName('', '');
By.xpath(0);
By.xpath(true);
By.xpath(() => {});
By.xpath();
By.xpath('', '');
